services:
  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    env_file: .env

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - auth_service

  photo_service:
    build: ./photo_service
    ports:
      - "8003:8003"
    env_file: .env
    volumes:
      - ./photo_service/static/uploads:/app/static/uploads
    depends_on:
      - user_service

  gateway:
    build: ./gateway
    ports:
      - "8080:80" # Exposes port 80 from the container as 8080 on your machine.
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - user_service
      - photo_service
